CREATE TABLE EMPLOYEE (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	 
	name varchar(255) not null,
	address varchar(2000)	 
);

create sequence employee_sequence start with 1 increment by 1;

insert into EMPLOYEE (name,address) values ('John','Chicago');